language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
script:
  - 'export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)'
  - 'echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$BRANCH" == "stable" ]; then npm run appr; fi'
