language: node_js
node_js:
  - "13"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - alfa
    - stable
script:
  - 'echo "$DECRYPT_PASSWORD" | yarn decrypt'
  - 'yarn test'
  - 'export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)'
  - 'echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$BRANCH" == "stable" ]; then yarn appr; fi'
