const SESSION = {
  SET_HOUSE_TO_SESSION: 'SET_HOUSE_TO_SESSION',
  DELETE_HOUSE_FROM_SESSION: 'DELETE_HOUSE_FROM_SESSION'
};

const SHOPPING_LIST = {
  SET_LIST: 'SET_LIST',
  REMOVE_ITEM: 'REMOVE_ITEM',
  ADD_ITEM: 'ADD_ITEM',
  EDIT_ITEM: 'EDIT_ITEM',
  INCREMENT_QUANTITY: 'INCREMENT_QUANTITY',
  DECREMENT_QUANTITY: 'DECREMENT_QUANTITY'
};

const USER = {
  SIGN_UP: 'SIGN_UP',
  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT',
  UPDATE_USER: 'UPDATE_USER'
}

export { SESSION, SHOPPING_LIST, USER };
