const SESSION = {
  SET_HOUSE_TO_SESSION: 'SET_HOUSE_TO_SESSION',
  DELETE_HOUSE_FROM_SESSION: 'DELETE_HOUSE_FROM_SESSION'
};

const SHOPPING_LIST = {
  SET_LIST: 'SET_LIST',
  REMOVE_ITEM: 'REMOVE_ITEM',
  ADD_ITEM: 'ADD_ITEM',
  EDIT_ITEM: 'EDIT_ITEM',
  INCREMENT_QUANTITY: 'INCREMENT_QUANTITY',
  DECREMENT_QUANTITY: 'DECREMENT_QUANTITY'
};

export { SESSION, SHOPPING_LIST };
