const SESSION = {
  INITIALIZE: 'INITIALIZE',

  SET_USER_TO_SESSION: 'SET_USER_TO_SESSION',
  SET_USER_TO_SESSION_SUCCESSFUL: 'SET_USER_TO_SESSION_SUCCESSFUL',
  DELETE_USER_FROM_SESSION: 'DELETE_USER_FROM_SESSION',
  DELETE_USER_FROM_SESSION_SUCCESSFUL: 'DELETE_USER_FROM_SESSION_SUCCESSFUL',
  UPDATE_USER_ON_SESSION: 'UPDATE_USER_ON_SESSION',
  UPDATE_USER_ON_SESSION_SUCCESSFUL: 'UPDATE_USER_ON_SESSION_SUCCESSFUL',

  SET_HOUSE_TO_SESSION: 'SET_HOUSE_TO_SESSION',
  SET_HOUSE_TO_SESSION_SUCCESSFUL: 'SET_HOUSE_TO_SESSION_SUCCESSFUL',
  DELETE_HOUSE_FROM_SESSION: 'DELETE_HOUSE_FROM_SESSION',
  DELETE_HOUSE_FROM_SESSION_SUCCESSFUL: 'DELETE_HOUSE_FROM_SESSION_SUCCESSFUL',
  UPDATE_HOUSE_ON_SESSION: 'UPDATE_HOUSE_ON_SESSION',
  UPDATE_HOUSE_ON_SESSION_SUCCESSFUL: 'UPDATE_HOUSE_ON_SESSION_SUCCESSFUL',

  EMPTY_SESSION: 'EMPTY_SESSION',
  EMPTY_SESSION_SUCCESSFUL: 'EMPTY_SESSION_SUCCESSFUL'
};

const SHOPPING_LIST = {
  SET_LIST: 'SET_LIST',
  REMOVE_ITEM: 'REMOVE_ITEM',
  ADD_ITEM: 'ADD_ITEM',
  EDIT_ITEM: 'EDIT_ITEM',
  INCREMENT_QUANTITY: 'INCREMENT_QUANTITY',
  DECREMENT_QUANTITY: 'DECREMENT_QUANTITY'
};


const INITIALIZE = 'INITIALIZE';

export { SESSION, SHOPPING_LIST, INITIALIZE };
